package pl.electronic_emergency_departament.webapi.tools;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import pl.electronic_emergency_departament.emd_data.model.TriageColour;
import pl.electronic_emergency_departament.emd_data.model.TriageModel;
import pl.electronic_emergency_departament.emd_data.repositories.TriageColourRepository;
import pl.electronic_emergency_departament.emd_data.repositories.TriageModelRepository;

@Configuration
public class DataInitializationConfig {

    @Bean
    CommandLineRunner initDatabaseWithColours(TriageColourRepository repository) {
        return args -> {
            if (repository.count() == 0) {
                repository.save(new TriageColour("Czerwony"));
                repository.save(new TriageColour("Pomarańczowy"));
                repository.save(new TriageColour("Żółty"));
                repository.save(new TriageColour("Zielony"));
                repository.save(new TriageColour("Niebieski"));
            }
        };
    }


    @Bean
    CommandLineRunner initDatabaseWithSymptoms(TriageModelRepository repository) {
        return args -> {
            if (repository.count() == 0) {
                repository.save(new TriageModel(null, "cc_abdominalcramping"));
                repository.save(new TriageModel(null, "cc_abdominaldistention"));
                repository.save(new TriageModel(null, "cc_abdominalpain"));
                repository.save(new TriageModel(null, "cc_abdominalpainpregnant"));
                repository.save(new TriageModel(null, "cc_abnormallab"));
                repository.save(new TriageModel(null, "cc_abscess"));
                repository.save(new TriageModel(null, "cc_addictionproblem"));
                repository.save(new TriageModel(null, "cc_agitation"));
                repository.save(new TriageModel(null, "cc_alcoholintoxication"));
                repository.save(new TriageModel(null, "cc_alcoholproblem"));
                repository.save(new TriageModel(null, "cc_allergicreaction"));
                repository.save(new TriageModel(null, "cc_alteredmentalstatus"));
                repository.save(new TriageModel(null, "cc_animalbite"));
                repository.save(new TriageModel(null, "cc_ankleinjury"));
                repository.save(new TriageModel(null, "cc_anklepain"));
                repository.save(new TriageModel(null, "cc_anxiety"));
                repository.save(new TriageModel(null, "cc_arminjury"));
                repository.save(new TriageModel(null, "cc_armpain"));
                repository.save(new TriageModel(null, "cc_armswelling"));
                repository.save(new TriageModel(null, "cc_assaultvictim"));
                repository.save(new TriageModel(null, "cc_asthma"));
                repository.save(new TriageModel(null, "cc_backpain"));
                repository.save(new TriageModel(null, "cc_bleeding_bruising"));
                repository.save(new TriageModel(null, "cc_blurredvision"));
                repository.save(new TriageModel(null, "cc_bodyfluidexposure"));
                repository.save(new TriageModel(null, "cc_breastpain"));
                repository.save(new TriageModel(null, "cc_breathingdifficulty"));
                repository.save(new TriageModel(null, "cc_breathingproblem"));
                repository.save(new TriageModel(null, "cc_burn"));
                repository.save(new TriageModel(null, "cc_cardiacarrest"));
                repository.save(new TriageModel(null, "cc_cellulitis"));
                repository.save(new TriageModel(null, "cc_chestpain"));
                repository.save(new TriageModel(null, "cc_chesttightness"));
                repository.save(new TriageModel(null, "cc_chills"));
                repository.save(new TriageModel(null, "cc_coldlikesymptoms"));
                repository.save(new TriageModel(null, "cc_confusion"));
                repository.save(new TriageModel(null, "cc_conjunctivitis"));
                repository.save(new TriageModel(null, "cc_constipation"));
                repository.save(new TriageModel(null, "cc_cough"));
                repository.save(new TriageModel(null, "cc_cyst"));
                repository.save(new TriageModel(null, "cc_decreasedbloodsugar_symptomatic"));
                repository.save(new TriageModel(null, "cc_dehydration"));
                repository.save(new TriageModel(null, "cc_dentalpain"));
                repository.save(new TriageModel(null, "cc_depression"));
                repository.save(new TriageModel(null, "cc_detoxevaluation"));
                repository.save(new TriageModel(null, "cc_diarrhea"));
                repository.save(new TriageModel(null, "cc_dizziness"));
                repository.save(new TriageModel(null, "cc_drug_alcoholassessment"));
                repository.save(new TriageModel(null, "cc_drugproblem"));
                repository.save(new TriageModel(null, "cc_dyspnea"));
                repository.save(new TriageModel(null, "cc_dysuria"));
                repository.save(new TriageModel(null, "cc_earpain"));
                repository.save(new TriageModel(null, "cc_earproblem"));
                repository.save(new TriageModel(null, "cc_edema"));
                repository.save(new TriageModel(null, "cc_elbowpain"));
                repository.save(new TriageModel(null, "cc_elevatedbloodsugar_nosymptoms"));
                repository.save(new TriageModel(null, "cc_elevatedbloodsugar_symptomatic"));
                repository.save(new TriageModel(null, "cc_emesis"));
                repository.save(new TriageModel(null, "cc_epigastricpain"));
                repository.save(new TriageModel(null, "cc_epistaxis"));
                repository.save(new TriageModel(null, "cc_exposuretostd"));
                repository.save(new TriageModel(null, "cc_extremitylaceration"));
                repository.save(new TriageModel(null, "cc_extremityweakness"));
                repository.save(new TriageModel(null, "cc_eyeinjury"));
                repository.save(new TriageModel(null, "cc_eyepain"));
                repository.save(new TriageModel(null, "cc_eyeproblem"));
                repository.save(new TriageModel(null, "cc_eyeredness"));
                repository.save(new TriageModel(null, "cc_facialinjury"));
                repository.save(new TriageModel(null, "cc_faciallaceration"));
                repository.save(new TriageModel(null, "cc_facialpain"));
                repository.save(new TriageModel(null, "cc_facialswelling"));
                repository.save(new TriageModel(null, "cc_fall"));
                repository.save(new TriageModel(null, "cc_fall_65"));
                repository.save(new TriageModel(null, "cc_fatigue"));
                repository.save(new TriageModel(null, "cc_femaleguproblem"));
                repository.save(new TriageModel(null, "cc_fever"));
                repository.save(new TriageModel(null, "cc_fever_75yearsorolder"));
                repository.save(new TriageModel(null, "cc_fever_9weeksto74years"));
                repository.save(new TriageModel(null, "cc_feverimmunocompromised"));
                repository.save(new TriageModel(null, "cc_fingerinjury"));
                repository.save(new TriageModel(null, "cc_fingerpain"));
                repository.save(new TriageModel(null, "cc_fingerswelling"));
                repository.save(new TriageModel(null, "cc_flankpain"));
                repository.save(new TriageModel(null, "cc_follow_upcellulitis"));
                repository.save(new TriageModel(null, "cc_footinjury"));
                repository.save(new TriageModel(null, "cc_footpain"));
                repository.save(new TriageModel(null, "cc_footswelling"));
                repository.save(new TriageModel(null, "cc_foreignbodyineye"));
                repository.save(new TriageModel(null, "cc_fulltrauma"));
                repository.save(new TriageModel(null, "cc_generalizedbodyaches"));
                repository.save(new TriageModel(null, "cc_gibleeding"));
                repository.save(new TriageModel(null, "cc_giproblem"));
                repository.save(new TriageModel(null, "cc_groinpain"));
                repository.save(new TriageModel(null, "cc_hallucinations"));
                repository.save(new TriageModel(null, "cc_handinjury"));
                repository.save(new TriageModel(null, "cc_handpain"));
                repository.save(new TriageModel(null, "cc_headache"));
                repository.save(new TriageModel(null, "cc_headache_newonsetornewsymptoms"));
                repository.save(new TriageModel(null, "cc_headache_recurrentorknowndxmigraines"));
                repository.save(new TriageModel(null, "cc_headachere_evaluation"));
                repository.save(new TriageModel(null, "cc_headinjury"));
                repository.save(new TriageModel(null, "cc_headlaceration"));
                repository.save(new TriageModel(null, "cc_hematuria"));
                repository.save(new TriageModel(null, "cc_hemoptysis"));
                repository.save(new TriageModel(null, "cc_hippain"));
                repository.save(new TriageModel(null, "cc_homicidal"));
                repository.save(new TriageModel(null, "cc_hyperglycemia"));
                repository.save(new TriageModel(null, "cc_hypertension"));
                repository.save(new TriageModel(null, "cc_hypotension"));
                repository.save(new TriageModel(null, "cc_influenza"));
                repository.save(new TriageModel(null, "cc_ingestion"));
                repository.save(new TriageModel(null, "cc_insectbite"));
                repository.save(new TriageModel(null, "cc_irregularheartbeat"));
                repository.save(new TriageModel(null, "cc_jawpain"));
                repository.save(new TriageModel(null, "cc_jointswelling"));
                repository.save(new TriageModel(null, "cc_kneeinjury"));
                repository.save(new TriageModel(null, "cc_kneepain"));
                repository.save(new TriageModel(null, "cc_laceration"));
                repository.save(new TriageModel(null, "cc_leginjury"));
                repository.save(new TriageModel(null, "cc_legpain"));
                repository.save(new TriageModel(null, "cc_legswelling"));
                repository.save(new TriageModel(null, "cc_lethargy"));
                repository.save(new TriageModel(null, "cc_lossofconsciousness"));
                repository.save(new TriageModel(null, "cc_maleguproblem"));
                repository.save(new TriageModel(null, "cc_mass"));
                repository.save(new TriageModel(null, "cc_medicalproblem"));
                repository.save(new TriageModel(null, "cc_medicalscreening"));
                repository.save(new TriageModel(null, "cc_medicationproblem"));
                repository.save(new TriageModel(null, "cc_medicationrefill"));
                repository.save(new TriageModel(null, "cc_migraine"));
                repository.save(new TriageModel(null, "cc_modifiedtrauma"));
                repository.save(new TriageModel(null, "cc_motorcyclecrash"));
                repository.save(new TriageModel(null, "cc_motorvehiclecrash"));
                repository.save(new TriageModel(null, "cc_multiplefalls"));
                repository.save(new TriageModel(null, "cc_nasalcongestion"));
                repository.save(new TriageModel(null, "cc_nausea"));
                repository.save(new TriageModel(null, "cc_nearsyncope"));
                repository.save(new TriageModel(null, "cc_neckpain"));
                repository.save(new TriageModel(null, "cc_neurologicproblem"));
                repository.save(new TriageModel(null, "cc_numbness"));
                repository.save(new TriageModel(null, "cc_oralswelling"));
                repository.save(new TriageModel(null, "cc_otalgia"));
                repository.save(new TriageModel(null, "cc_other"));
                repository.save(new TriageModel(null, "cc_overdose_accidental"));
                repository.save(new TriageModel(null, "cc_overdose_intentional"));
                repository.save(new TriageModel(null, "cc_pain"));
                repository.save(new TriageModel(null, "cc_palpitations"));
                repository.save(new TriageModel(null, "cc_panicattack"));
                repository.save(new TriageModel(null, "cc_pelvicpain"));
                repository.save(new TriageModel(null, "cc_poisoning"));
                repository.save(new TriageModel(null, "cc_post_opproblem"));
                repository.save(new TriageModel(null, "cc_psychiatricevaluation"));
                repository.save(new TriageModel(null, "cc_psychoticsymptoms"));
                repository.save(new TriageModel(null, "cc_rapidheartrate"));
                repository.save(new TriageModel(null, "cc_rash"));
                repository.save(new TriageModel(null, "cc_rectalbleeding"));
                repository.save(new TriageModel(null, "cc_rectalpain"));
                repository.save(new TriageModel(null, "cc_respiratorydistress"));
                repository.save(new TriageModel(null, "cc_ribinjury"));
                repository.save(new TriageModel(null, "cc_ribpain"));
                repository.save(new TriageModel(null, "cc_seizure_newonset"));
                repository.save(new TriageModel(null, "cc_seizure_priorhxof"));
                repository.save(new TriageModel(null, "cc_seizures"));
                repository.save(new TriageModel(null, "cc_shortnessofbreath"));
                repository.save(new TriageModel(null, "cc_shoulderinjury"));
                repository.save(new TriageModel(null, "cc_shoulderpain"));
                repository.save(new TriageModel(null, "cc_sicklecellpain"));
                repository.save(new TriageModel(null, "cc_sinusproblem"));
                repository.save(new TriageModel(null, "cc_skinirritation"));
                repository.save(new TriageModel(null, "cc_skinproblem"));
                repository.save(new TriageModel(null, "cc_sorethroat"));
                repository.save(new TriageModel(null, "cc_stdcheck"));
                repository.save(new TriageModel(null, "cc_strokealert"));
                repository.save(new TriageModel(null, "cc_suicidal"));
                repository.save(new TriageModel(null, "cc_suture_stapleremoval"));
                repository.save(new TriageModel(null, "cc_swallowedforeignbody"));
                repository.save(new TriageModel(null, "cc_syncope"));
                repository.save(new TriageModel(null, "cc_tachycardia"));
                repository.save(new TriageModel(null, "cc_testiclepain"));
                repository.save(new TriageModel(null, "cc_thumbinjury"));
                repository.save(new TriageModel(null, "cc_tickremoval"));
                repository.save(new TriageModel(null, "cc_toeinjury"));
                repository.save(new TriageModel(null, "cc_toepain"));
                repository.save(new TriageModel(null, "cc_trauma"));
                repository.save(new TriageModel(null, "cc_unresponsive"));
                repository.save(new TriageModel(null, "cc_uri"));
                repository.save(new TriageModel(null, "cc_urinaryfrequency"));
                repository.save(new TriageModel(null, "cc_urinaryretention"));
                repository.save(new TriageModel(null, "cc_urinarytractinfection"));
                repository.save(new TriageModel(null, "cc_vaginalbleeding"));
                repository.save(new TriageModel(null, "cc_vaginaldischarge"));
                repository.save(new TriageModel(null, "cc_vaginalpain"));
                repository.save(new TriageModel(null, "cc_weakness"));
                repository.save(new TriageModel(null, "cc_wheezing"));
                repository.save(new TriageModel(null, "cc_withdrawal_alcohol"));
                repository.save(new TriageModel(null, "cc_woundcheck"));
                repository.save(new TriageModel(null, "cc_woundinfection"));
                repository.save(new TriageModel(null, "cc_woundre_evaluation"));
                repository.save(new TriageModel(null, "cc_wristinjury"));
                repository.save(new TriageModel(null, "cc_wristpain"));
            }
        };
    }

}